apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-api
  template:
    metadata:
      labels:
        app: conv-api
    spec:
      containers:
      - name: conv-api
        image: antonlarichev/conv-api:1.0
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_PASSWORD
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_HOSTNAME
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: conv-app-data
          mountPath: /opt/app/uploads
      volumes:
      - name: conv-app-data
        persistentVolumeClaim:
          claimName: conv-api-pvc 
