apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conv-app-ingress
  labels:
    name: conv-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: conv-app.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: conv-app-clusterip
            port: 
              number: 80
