apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12.10
        env:
          - name: SEED_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: SEED_USERNAME
          - name: SEED_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: SEED_USER_PASSWORD
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
        ports:
        - containerPort: 5672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc 
