apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-service
  template:
    metadata:
      labels:
        app: conv-service
    spec:
      containers:
      - name: conv-service
        image: antonlarichev/conv-service:1.0
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_PASSWORD
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_HOSTNAME
          - name: AMQP_QUEUE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: AMQP_EXCHANGE
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
