apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-clusterip
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
