apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | b64enc }}
  SEED_USERNAME: {{ .Values.rabbitmq.user | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc }}
  SEED_USER_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  AMQP_EXCHANGE: {{ .Values.rabbitmq.amqp_exchange | b64enc }}
  AMQP_USER: {{ .Values.rabbitmq.user | b64enc }}
  AMQP_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  AMQP_HOSTNAME: {{ printf "%s-clusterip" .Values.rabbitmq.name  | b64enc }}
  AMQP_QUEUE: {{ .Values.rabbitmq.amqp_queue | b64enc }}